rosbag_converter_node:
  ros__parameters:
    path_in_ros1_bag_file: "/home/mfc/bags/038/038.bag"
    path_out_ros2_serialized_binary: "/home/mfc/bags/038/038.proto_rosbag2"
    print_type_correspondences_1_to_2: false
